# Generated by Django 3.2.7 on 2021-09-29 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='publications',
            new_name='products',
        ),
    ]
